---

- name: Install nginx_l4_lb
  command: kubectl apply -f -
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'configmap.yml.j2') }}"
    - "{{ lookup('template', 'daemonset.yml.j2') }}"

# vim: set ts=2 sw=2:
